{ ... }:
{
  imports = [
    ./nixvim/default.nix
    ./nvf/default.nix
    ./brave.nix
    ./firefox.nix
    ./fileSharing.nix
    ./foot.nix
    ./git.nix
    ./kitty.nix
    ./lf.nix
    ./msmtp.nix
    ./nautilus.nix
    ./open-webui.nix
    ./protonmail.nix
    ./qemu.nix
    ./spotify.nix
    ./ssh.nix
    ./syncthing.nix
    ./thunar.nix
    ./thunderbird.nix
    ./tmux.nix
    ./virtualbox.nix
    ./winboat.nix
    ./yazi.nix
    ./zsh.nix
  ];
}
